### ISSUE TITLE
Change FixedPoint to only support From<U128> and adjust tests

### ISSUE THREAD

**Issue by dpaiton** [delvtech/hyperdrive-rs#127]
Modify the [U256 from](https://github.com/delvtech/hyperdrive-rs/blob/83b2f812f859b23b3bdc7401b9c421e8786c2c46/crates/fixed-point/src/lib.rs#L67-L72) impl to check if the value fits in a U128. If so, do the conversion. Else (value is > U128::max) throw an error.

Adjust the tests to use U128::max instead of U256::max everywhere. 

We should make sure to add docstrings somewhere to indicate to the user that FixedPoint has max U128 support.

**Comment by ryangoree** [comment]
The [catalyst for this issue](https://github.com/delvtech/hyperdrive-rs/issues/20#issuecomment-2089272326) was the fact that we couldn't divide a `FixedPoint` instance that was `> U256::MAX / 1e18`. The proposed solution was to use smaller inputs that wouldn't overflow the `U256` when scaled up by `1e18`.

With #186 landing, this issue has been resolved and the lib uses `U512` as an intermediary type in `mul_div_down`/`mul_div_up` to avoid unexpected overflows given valid inputs.

This has a few implications:
- We don't have to change to a `u128` anymore just to avoid this error.
- The solidity still has this limitation, so tests will still need to limit max values to `U256::MAX / 1e18` like so:
   https://github.com/delvtech/hyperdrive-rs/blob/5987b7bb7dd26b41215c9b3cf4a8cdc1b5d29e25/crates/fixedpointmath/src/math.rs#L240-L243
- Where we still want tighter bounds, we can swap `FixedPoint<U256>` with `FixedPoint<u128>`, `FixedPoint<i128>`, or `FixedPoint<I256>`
