### ISSUE TITLE
k<y error when calculating PnL (testnet)

### ISSUE THREAD

**Issue by lajarre** [delvtech/hyperdrive-rs#16]
My goal it to compute PnLs for traders at different points in time in the past, leveraging `State` and `calculate_close_long`. But this results in an error.

I made an example minimal reproduction case, based on Sepolia testnet Hyperdrive `0x3928` and this [OpenLong event](https://sepolia.etherscan.io/tx/0x9a06d8ebc7f35429a1bc7fba0ddd2b510bbb02d8477f3bff53a95ec8ab2891d6#eventlog), ready to test in the following repo: https://github.com/lajarre/hyperdrive-pnl-issue 

Essentially, the code is doing

```rust
        let pool_config = contract
            .get_pool_config()
            .block(CURRENT_BLOCK_NUM)
            .call()
            .await?;
        let pool_info = contract
            .get_pool_info()
            .block(CURRENT_BLOCK_NUM)
            .call()
            .await?;
        let state = State::new(pool_config, pool_info);

        let close_long =
            state.calculate_close_long(evt.bond_amount, evt.maturity_time, at_timestamp);
```

with `CURRENT_BLOCK_NUM` a past block where we are interested in having the PnLs computed from.

This produces the following runtime error:

```
thread 'main' panicked at <>/crates/hyperdrive-math/src/yield_space.rs:157:14:
called `Result::unwrap()` on an `Err` value: calculate_shares_out_given_bonds_in_down_safe: k = 64563.061039611084245350 < 70831.661360654143172192 = y
```

Perhaps is the state wrongly initialized? For now I fail to see where my usage of the library is wrong.

Any help debugging this would be greatly appreciated 🙏

**Comment by slundqui** [comment]
The error you're running into here is due to the long not being able to be closed at this point in time due to insufficient liquidity (longs are always guaranteed to be closed at maturity). We can definitely improve error messaging here to be more user friendly.

**Comment by lajarre** [comment]
Thank your for the clarification.

Knowing this, do you have a suggestion for how to achieve my goal, namely compute PnLs at a given point in time, for a given position? A solution seems to be to assume that the position is only closed at maturity and not before, so `state.calculate_close_long(evt.bond_amount, evt.maturity_time, evt.maturity_time)`.

**Comment by dpaiton** [comment]
We're working on a feature that will let you boot into a fork of any remote chain and execute sequences of trades. In that case you can fork, add liquidity, then mock closing the trades. 

In the interim, I think your solution is correct. You should report "PNL" as if the use held their longs until maturity.
