### ISSUE TITLE
Improved Testing of the Rust SDK

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive-rs#20]
There were some issues reported a while ago by @slundqui. We'll need to review these calculations to see if we can find the source of the issue. We should also take the time to improve the test coverage. The current testing methodology is pretty good, but we don't test with different configurations, which really limits the robustness of the testing.

We should differentially test every rust function against Solidity.

**Comment by dpaiton** [comment]
@ryangoree 
> Alternatively the FixedPoint library could be refactored to handle these cases internally. 

I think this is the move. We should refactor fixedpoint to return results instead of panic https://github.com/delvtech/hyperdrive-rs/issues/99

This would clean up **a lot** of testing code.

**Comment by dpaiton** [comment]
https://github.com/delvtech/hyperdrive-rs/issues/127

**Comment by dpaiton** [comment]
Updating test chain to support fuzzing over multiple states: https://github.com/delvtech/hyperdrive-rs/issues/128

**Comment by dpaiton** [comment]
panic / result issue resolved as much as we want by https://github.com/delvtech/hyperdrive-rs/pull/113

**Comment by dpaiton** [comment]
closing in favor of new smaller issues
