### ISSUE TITLE
implement `calculate_remove_liquidity`

### ISSUE THREAD

**Issue by ryangoree** [delvtech/hyperdrive-rs#22]
Add a function to the Rust SDK that calculates the amount of `proceeds` and `withdrawal_shares` received for removing liquidity. Traders and UIs could use this to preview their returns without hitting the chain.

**Comment by sentilesdal** [comment]
Delayed a bit by the 1.0.5 upgrade but,

Two landed:
#7, #11
One ready to go:
#17 - ShouldShortCircuit and LongEdgeCase helpers

Not in PR, but code written:
DistributeExcessIdleShortProceeds, DistributeExcessIdle

**Comment by sentilesdal** [comment]
Delayed a bit by the 1.0.5 upgrade but,

Two landed:
https://github.com/delvtech/hyperdrive-rs/pull/7, https://github.com/delvtech/hyperdrive-rs/pull/11
One ready to go:
https://github.com/delvtech/hyperdrive-rs/pull/17 - `distribute_excess_idle`
One draft PR:
https://github.com/delvtech/hyperdrive-rs/pull/100 - `calculate_remove_liquidity`

**Comment by sentilesdal** [comment]
Three landed:
https://github.com/delvtech/hyperdrive-rs/pull/7, https://github.com/delvtech/hyperdrive-rs/pull/11
https://github.com/delvtech/hyperdrive-rs/pull/17 - distribute_excess_idle
One Ready to Go:
https://github.com/delvtech/hyperdrive-rs/pull/100 - calculate_remove_liquidity

**Comment by sentilesdal** [comment]
#100 needs https://github.com/delvtech/hyperdrive/pull/1049 to land first in order to have the exact results
