### ISSUE TITLE
Auto-generate Rust Documentation

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive-rs#27]
We should publish the auto-generated rust docs from the Rust SDK. We could also publish a docs portal for the Rust SDK and other SDKs.

**Comment by dpaiton** [comment]
whoever dives into this should look into latex rendering (e.g. via [ktex_doc](https://docs.rs/katex-doc/0.1.0/katex_doc/)). If we are able to do it without too much friction, then I propose we use latex style docs for function (& above) docstrings, and human-readable docs for inline equations.

**Comment by dpaiton** [comment]
All solutions that I've found are variations of using the `--html-in-header` flag to inject html that runs [katex](https://www.npmjs.com/package/katex) javascript at runtime.

I don't think we need this now, but one interesting find is that you can also use [`--html-before-content`](https://github.com/rust-lang/rust/issues/34261#issuecomment-1042696542) to define global LaTeX equation macros that then can be used throughout. 

Here's an example repo the renders latex docs: https://docs.rs/levenberg-marquardt/latest/levenberg_marquardt/

**Comment by dpaiton** [comment]
ok, I think I got a handle on it. I'll take lead on this
<img width="1022" alt="image" src="https://github.com/delvtech/hyperdrive-rs/assets/153468/36a814c4-df23-4ea4-9e6a-90944c62dd43">
