### ISSUE TITLE
Standardize units in the Rust SDK

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive-rs#31]
There are some functions that could return base but don't. Investigate whether or not it makes sense to update these units.

**Comment by wakamex** [comment]
check this out @jrhea

**Comment by wakamex** [comment]
see the comment above for what I have in mind as a return object for each trade function (already coded in python!) @jalextowle @dpaiton

**Comment by wakamex** [comment]
moving discussion to https://github.com/delvtech/hyperdrive-rs/issues/63#issue-2276674589
