### ISSUE TITLE
[CRASH REPORT] Calculating max short in rust crashes with specific parameters

### ISSUE THREAD

**Issue by slundqui** [delvtech/hyperdrive-rs#42]
### Description

Calling `calc_max_short` in the rust SDK breaks with an `arithmetic operation overflow` error

### Expected Behavior

`calc_max_short` doesn't crash

### Actual Behavior

`calc_max_short` crashes with an error

### Steps to Reproduce

1. Deploy a hyperdrive pool with a position duration of a week, target fixed rate of 5%, initial liquidity of 100,000,000 base. This results in a time_stretch of 0.00087344336337973.
2. Call `calc_max_short` with a budget of 100,000 base.

Playing around with parameters, it seems that `calc_max_short` doesn't crash when the position duration is > 29 days, but does crash when position duration <= 28 days.

Additionally, with a position duration of a week, adjusting the budget to be 1e9 base doesn't crash, but setting a budget of 100,000 base does crash.

**Comment by dpaiton** [comment]
Closing in favor of #45
